spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console  # url: localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: none  # JPA가 테이블을 자동 생성/업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: h2
      mode: embedded
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
