CREATE TABLE url (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url VARCHAR(255),
    original_url VARCHAR(2048),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    INDEX idx_short_url_is_deleted (short_url, is_deleted)
);